PROMPT ====================================================
PROMPT CREATE TABLE CMS_OPERATION_SCREENS
PROMPT ====================================================

PROMPT TABLE CMS_OPERATION_SCREENS
CREATE TABLE CMS_OPERATION_SCREENS(
 ID                             VARCHAR2(50) NOT NULL
,SEQ                            NUMBER(38,0)
,ORDINAL                        NUMBER(38,0)
,DESCRIPTION                    VARCHAR2(80)
,OP_ID                          VARCHAR2(50)
,NAME                           VARCHAR2(30)
,DEFAULT_ELEMENT                VARCHAR2(30)
,ACTIVE_ELEMENT                 VARCHAR2(30)
,STATE_ID                       VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL
,CREATE_DATE                    DATE DEFAULT SYSDATE
,ADDITIONAL_HTML_PARAM          VARCHAR2(4000)
,IS_LOGOUT                      VARCHAR2(3)  DEFAULT 'YES'
,IS_MENU                        VARCHAR2(3)  DEFAULT 'YES'
,IS_NEW_WINDOW                  VARCHAR2(3)  DEFAULT 'NO'
)
/

PROMPT ====================================================
PROMPT CREATE COMMENTS
PROMPT ====================================================

PROMPT ====================================================
PROMPT ALTER TABLE CMS_OPERATION_SCREENS
PROMPT ====================================================

ALTER TABLE CMS_OPERATION_SCREENS ADD ID VARCHAR2(50) NOT NULL
/
ALTER TABLE CMS_OPERATION_SCREENS ADD SEQ NUMBER(38,0)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD ORDINAL NUMBER(38,0)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD DESCRIPTION VARCHAR2(80)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD OP_ID VARCHAR2(50)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD NAME VARCHAR2(30)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD DEFAULT_ELEMENT VARCHAR2(30)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD ACTIVE_ELEMENT VARCHAR2(30)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD ADDITIONAL_HTML_PARAM VARCHAR2(4000)
/
ALTER TABLE CMS_OPERATION_SCREENS ADD STATE_ID VARCHAR2(10)     DEFAULT 'INIT' NOT NULL
/
ALTER TABLE CMS_OPERATION_SCREENS ADD CREATE_DATE DATE          DEFAULT SYSDATE
/
ALTER TABLE CMS_OPERATION_SCREENS ADD IS_LOGOUT VARCHAR2(3)     DEFAULT 'YES'
/
ALTER TABLE CMS_OPERATION_SCREENS ADD IS_MENU VARCHAR2(3)       DEFAULT 'YES'
/
ALTER TABLE CMS_OPERATION_SCREENS ADD IS_NEW_WINDOW VARCHAR2(3) DEFAULT 'NO'
/
PROMPT ====================================================
PROMPT INDEXES
PROMPT ====================================================

PROMPT INDEX OPSCR_NAME_OPID_UK
CREATE UNIQUE INDEX OPSCR_NAME_OPID_UK
  ON CMS_OPERATION_SCREENS(
    NAME,OP_ID
  )
/

PROMPT INDEX OPSCR_OPID_IDX
CREATE INDEX OPSCR_OPID_IDX
  ON CMS_OPERATION_SCREENS(
    OP_ID
  )
/

PROMPT INDEX OPSCR_PK
CREATE UNIQUE INDEX OPSCR_PK
  ON CMS_OPERATION_SCREENS(
    ID
  )
/

PROMPT INDEX OPSCR_state_idX
CREATE INDEX OPSCR_STATE_IDX
  ON CMS_OPERATION_SCREENS(
    STATE_ID
  )
/

PROMPT ====================================================
PROMPT CONSTRINTS
PROMPT ====================================================

PROMPT CONSTRINT OPSCR_PK
ALTER TABLE CMS_OPERATION_SCREENS
  ADD CONSTRAINT OPSCR_PK PRIMARY KEY (
    ID
  )
/

PROMPT CONSTRINT OPSCR_OPID_FK
ALTER TABLE CMS_OPERATION_SCREENS
  ADD CONSTRAINT OPSCR_OPID_FK FOREIGN KEY (
    OP_ID
  ) REFERENCES CMS_OPERATIONS(
    ID
  )
/

PROMPT CONSTRINT OPSCR_STATE_FK
ALTER TABLE CMS_OPERATION_SCREENS
  ADD CONSTRAINT OPSCR_STATE_FK FOREIGN KEY (
    STATE_ID
  ) REFERENCES CMS_STATES(
    ID
  )


PROMPT ====================================================
PROMPT SEQUENCES
PROMPT ===================================================

PROMPT SEQUENCE OPSCR
CREATE SEQUENCE OPSCR_SEQ
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
/

COMMIT;
