PROMPT ====================================================
PROMPT CREATE TABLE CMS_SCREEN_ELEMENTS
PROMPT ====================================================

PROMPT TABLE CMS_SCREEN_ELEMENTS
CREATE TABLE CMS_SCREEN_ELEMENTS(
 ID                              VARCHAR2(50) NOT NULL
,SEQ                             NUMBER(38, 0)
,ORDINAL                         NUMBER(38, 0)
,DESCRIPTION                     VARCHAR2(80)
,OPSCR_ID                        VARCHAR2(50)
,TYPE                            VARCHAR2(30)
,NAME                            VARCHAR2(30)
,STYLE                           VARCHAR2(4000)
,CLASS                           VARCHAR2(30)
,FUNCTION_CHECK                  VARCHAR2(4000)
,FUNCTION_SQL                    VARCHAR2(4000)
,FUNCTION_PROC                   VARCHAR2(4000)
,FUNCTION_SCR                    VARCHAR2(4000)
,FUNCTION_VAL                    VARCHAR2(4000)
,FUNCTION_VAL_BEFORE             VARCHAR2(4000)
,FUNCTION_VAL_AFTER              VARCHAR2(4000)
,FUNCTION_HIDE                   VARCHAR2(4000)
,GOTOSCR_ID                      VARCHAR2(50)
,VALUE                           VARCHAR2(4000)
,CLEAR_FIELD                     CHAR(3)          DEFAULT 'NO'       NOT NULL
,IS_ROW                          CHAR(3)          DEFAULT 'YES'       NOT NULL
,HTML_BEFORE_ELEM                VARCHAR2(4000)
,HTML_AFTER_ELEM                 VARCHAR2(4000)
,STATE_ID                        VARCHAR2(10)     DEFAULT 'ACTIVE'      NOT NULL
,CREATE_DATE                     DATE             DEFAULT SYSDATE
,COMMENTS                        VARCHAR2(2000)
,LABEL                           VARCHAR2(4000)
,REFRESH_CONTENT                 VARCHAR2(3)      DEFAULT 'NO'       NOT NULL
,REFRESH_SCREEN                  VARCHAR2(3)      DEFAULT 'NO'       NOT NULL
,CONTAINER_STYLE                  VARCHAR2(4000)
,NEW_WINDOW                      VARCHAR2(30)
,FUNCTION_NEW_WINDOW             VARCHAR2(4000)
,NEW_WINDOW_IN_TAB               VARCHAR2(3)      DEFAULT 'YES'       NOT NULL
,TOOLTIP                         varchar2(4000)
)
/

PROMPT ====================================================
PROMPT CREATE COMMENTS
PROMPT ====================================================

PROMPT ====================================================
PROMPT ALTER TABLE CMS_SCREEN_ELEMENTS
PROMPT ====================================================

ALTER TABLE CMS_SCREEN_ELEMENTS ADD ID VARCHAR2(50) NOT NULL
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD SEQ NUMBER(38,0)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD ORDINAL NUMBER(38,0)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD DESCRIPTION VARCHAR2(80)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD OPSCR_ID VARCHAR2(50)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD TYPE VARCHAR2(30)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD NAME VARCHAR2(30)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD STYLE VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD CLASS VARCHAR2(30)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_CHECK VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_SQL VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_PROC VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_SCR VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_VAL VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_VAL_BEFORE VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_VAL_AFTER VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_HIDE VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD GOTOSCR_ID VARCHAR2(50)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD VALUE VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD CLEAR_FIELD CHAR(3) DEFAULT 'NO' NOT NULL
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD IS_ROW CHAR(3) DEFAULT 'YES' NOT NULL
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD HTML_BEFORE_ELEM VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD HTML_AFTER_ELEM VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD STATE_ID VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD CREATE_DATE DATE DEFAULT SYSDATE
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD COMMENTS VARCHAR2(2000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD LABEL VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD REFRESH_CONTENT VARCHAR2(3) DEFAULT 'NO' NOT NULL
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD REFRESH_SCREEN VARCHAR2(3) DEFAULT 'NO' NOT NULL
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD CONTAINER_STYLE VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD NEW_WINDOW VARCHAR2(30)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD FUNCTION_NEW_WINDOW VARCHAR2(4000)
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD NEW_WINDOW_IN_TAB VARCHAR2(3) DEFAULT 'YES' NOT NULL
/
ALTER TABLE CMS_SCREEN_ELEMENTS ADD TOOLTIP VARCHAR2(4000)
/

PROMPT ====================================================
PROMPT INDEXES
PROMPT ====================================================

PROMPT INDEX SCRELEM_OPSCR_ID_IDX
CREATE INDEX SCRELEM_OPSCR_ID_IDX
  ON CMS_SCREEN_ELEMENTS(
    OPSCR_ID
  )
/

PROMPT INDEX SCRELEM_PK
CREATE UNIQUE INDEX SCRELEM_PK
  ON CMS_SCREEN_ELEMENTS(
    ID
  )
/

PROMPT INDEX SCRELEM_STATE_IDX
CREATE INDEX SCRELEM_STATE_IDX
  ON CMS_SCREEN_ELEMENTS(
    STATE_ID
  )
/

PROMPT ====================================================
PROMPT CONSTRINTS
PROMPT ====================================================

PROMPT CONSTRINT SCRELEM_PK
ALTER TABLE CMS_SCREEN_ELEMENTS
  ADD CONSTRAINT SCRELEM_PK PRIMARY KEY (
    ID
  )
/

PROMPT CONSTRINT SCRELEM_OPSCR_FK
ALTER TABLE CMS_SCREEN_ELEMENTS
  ADD CONSTRAINT SCRELEM_OPSCR_ID_FK FOREIGN KEY (
    OPSCR_ID
  ) REFERENCES CMS_OPERATION_SCREENS(
    ID
  )
/

PROMPT CONSTRINT SCRELEM_OPSCR_FK
ALTER TABLE CMS_SCREEN_ELEMENTS
  ADD CONSTRAINT SCRELEM_GOTOSRC_ID_FK FOREIGN KEY (
    GOTOSRC_ID
  ) REFERENCES CMS_OPERATION_SCREENS(
    ID
  )
/

PROMPT CONSTRINT SCRELEM_STATE_FK
ALTER TABLE CMS_SCREEN_ELEMENTS
  ADD CONSTRAINT SCRELEM_STATE_FK FOREIGN KEY (
    STATE_ID
  ) REFERENCES STATES(
    ID
  )
/

PROMPT ====================================================
PROMPT SEQUENCES
PROMPT ===================================================

PROMPT SEQUENCE SCRELEM
CREATE SEQUENCE SCRELEM_SEQ
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
/

COMMIT;
